### ISSUE TITLE
Cannot find plug-in settings.

### ISSUE THREAD

**Issue by thanarious** [AlexVerrico/Octoprint-ThermalRunaway#6]
Maybe it's me...
Installed the plug-in, refreshed the octoprint interface as instructed, but I can't seem to be able to find the plug-in settings to set the proper temp and time limits anywhere. Don't see anything regarding the issue on the readme, either.
Thank for any help.

**Comment by thanarious** [comment]
OK, a restart of the server was needed, seems you'll have to properly update the post-install script then...

**Comment by AlexVerrico** [comment]
Octoprint always requests a restart when I install this plugin, so I'm not sure what went wrong.

**Comment by thanarious** [comment]
It only asked for a browser refresh on my case, hence the initial question.

**Comment by AlexVerrico** [comment]
Ok then, I will look into it at some point.
Cheers,
Alex.

**Comment by merrill-oakland** [comment]
This is still an issue. I just installed the plugin for the first time, and it asked me to reload instead of reboot. Had to reboot manually to get the plugin to show up. Only plugin I've seen this with.
I think your plugin might not be using a hook or mixin that normally requires a restart, but it does indeed need a restart to work (seemingly). 
I _think_ adding octoprint.plugin.RestartNeedingPlugin to https://github.com/AlexVerrico/Octoprint-ThermalRunaway/blob/master/octoprint_ThermalRunaway/__init__.py#L12 would fix it

**Comment by AlexVerrico** [comment]
Hmm, I'll have to take another look at this.

**Comment by StephanBeutel** [comment]
I had the same problem - deleting cookies solved the problem.

**Comment by AlexVerrico** [comment]
G'Day @merrill-oakland @StephanBeutel 
I believe that I have fixed this in the Dev branch now, thanks again for reporting the issue.
Cheers, Alex.
